//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iRecon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image_reco
    {
        public string Image_tested { get; set; }
        public string Image_testing { get; set; }
        public int Score { get; set; }
        public Nullable<decimal> Match_time { get; set; }
        public Nullable<int> Class_of_tested { get; set; }
        public Nullable<int> Class_of_testing { get; set; }
        public Nullable<int> Real_class_of_tested { get; set; }
    }
}
